const cars = [
    // Pegassi
    { name: "Pegassi Infernus", category: "Super", price: "$", basedOn: "Lamborghini Murciélago, Diablo, Pagani Zonda, Spyker C8", img: "" },
    { name: "Pegassi Monroe", category: "Sports Classic", price: "$", basedOn: "Lamborghini Miura, Ford GT40", img: "" },
    { name: "Pegassi Vacca", category: "Super", price: "$", basedOn: "Lamborghini Gallardo, Aventador LP 700-4", img: "" },
    { name: "Pegassi Zentorno", category: "Super", price: "$", basedOn: "Lamborghini Sesto Elemento, Veneno", img: "" },
    { name: "Pegassi Osiris", category: "Super", price: "$", basedOn: "Pagani Huayra, Ferrari LaFerrari", img: "" },
    { name: "Pegassi Reaper", category: "Super", price: "$", basedOn: "W Motors Lykan HyperSport", img: "" },
    { name: "Pegassi Tempesta", category: "Super", price: "$", basedOn: "Lamborghini Huracán, Lotus Esprit Concept", img: "" },
    { name: "Pegassi Infernus Classic", category: "Sports Classic", price: "$", basedOn: "Lamborghini Diablo", img: "" },
    { name: "Pegassi Torero", category: "Sports Classic", price: "$", basedOn: "Lamborghini Countach 25th Anniversary", img: "" },
    { name: "Pegassi Tezeract", category: "Super Electric", price: "$", basedOn: "Lamborghini Terzo Millennio, SRT Tomahawk, Aventador SV", img: "" },
    { name: "Pegassi Toros", category: "SUV", price: "$", basedOn: "Lamborghini Urus", img: "" },
    { name: "Pegassi Zorrusso", category: "Super", price: "$", basedOn: "Italdesign Zerouno", img: "" },
    { name: "Pegassi Toreador", category: "Sports Classic", price: "$", basedOn: "Lamborghini Marzal", img: "" },
    { name: "Pegassi Ignus", category: "Super", price: "$", basedOn: "Lamborghini Sián FKP 37", img: "" },
    { name: "Pegassi Ignus Armado", category: "Super Armored", price: "$", basedOn: "Lamborghini Sián FKP 37", img: "" },
    { name: "Pegassi Torero XO", category: "Super", price: "$", basedOn: "Lamborghini Countach LPI 800-4", img: "" },
    
    // Grotti
    { name: "Grotti Turismo", category: "Sports", price: "$", basedOn: "Ferrari 360", img: "" },
    { name: "Grotti Carbonizzare", category: "GT", price: "$", basedOn: "Ferrari F12, Aston Martin V12 Zagato", img: "" },
    { name: "Grotti Cheetah", category: "Super", price: "$", basedOn: "Ferrari Enzo, GTA Spano, Pagani Zonda", img: "" },
    { name: "Grotti Stinger", category: "Classic GT Convertible", price: "$", basedOn: "Ferrari 250 GT California Spyder, Ferrari 275 GTS/4 NART", img: "" },
    { name: "Grotti Stinger GT", category: "Classic GT", price: "$", basedOn: "Ferrari 250 GTO, Ferrari 330 GTO", img: "" },
    { name: "Grotti Turismo R", category: "Super", price: "$", basedOn: "Ferrari LaFerrari, Faralli & Mazzanti Evantra", img: "" },
    { name: "Grotti Bestia GTS", category: "GT", price: "$", basedOn: "Ferrari FF, Ferrari GTC4Lusso", img: "" },
    { name: "Grotti X80 Proto", category: "Super Prototype", price: "$", basedOn: "Ferrari F80 Concept", img: "" },
    { name: "Grotti Brioso R/A", category: "Compact", price: "$", basedOn: "Fiat 500 Abarth, Abarth 500 Assetto Corse", img: "" },
    { name: "Grotti Turismo Classic", category: "Sports Classic", price: "$", basedOn: "Ferrari F40, Ferrari Testarossa", img: "" },
    { name: "Grotti Cheetah Classic", category: "Sports Classic", price: "$", basedOn: "Ferrari Testarossa, Ferrari 328 GTB/GTS", img: "" },
    { name: "Grotti Visione", category: "Super", price: "$", basedOn: "Ferrari Xezri Competizione, McLaren P1 GTR", img: "" },
    { name: "Grotti Vigilante", category: "Super Modified", price: "$", basedOn: "Batmóvil (varias versiones)", img: "" },
    { name: "Grotti GT500", category: "Sports Classic", price: "$", basedOn: "Ferrari 250 GT SWB, BMW 507", img: "" },
    { name: "Grotti Itali GTO", category: "GT", price: "$", basedOn: "Ferrari 812 Superfast", img: "" },
    { name: "Grotti Furia", category: "Super", price: "$", basedOn: "Pininfarina Battista", img: "" },
    { name: "Grotti Brioso 300", category: "Classic Compact", price: "$", basedOn: "Fiat 500", img: "" },
    { name: "Grotti Brioso 300 (Ancho)", category: "Classic Compact Widebody", price: "$", basedOn: "Fiat Abarth TCR 1000 Berlina Corsa", img: "" },
    { name: "Grotti Itali RSX", category: "Super", price: "$", basedOn: "Ferrari SF90 Stradale, Ferrari F8 Tributo", img: "" },
    { name: "Grotti Itali GTO Stinger TT", category: "GT", price: "$", basedOn: "Ferrari Roma", img: "" },
    { name: "Grotti Turismo Omaggio", category: "Sports", price: "$", basedOn: "Ferrari F8 Tributo", img: "" }
];
