// Base de datos de aviones
const aviones = [
    { nombre: "Alpha-Z1", foto: "img-coches/aviones/alpha-z1.png", compra: "" },
    { nombre: "Mammoth Avenger", foto: "img-coches/aviones/avenger.png", compra: "" },
    { nombre: "Avión de carga", foto: "img-coches/aviones/avion-de-carga.png", compra: "" },
    { nombre: "Western Avioneta fumigadora", foto: "img-coches/aviones/avioneta-fumigadora-duster.png", compra: "" },
    { nombre: "Western Besra", foto: "img-coches/aviones/western-besra.png", compra: "" },
    { nombre: "Bombushka", foto: "img-coches/aviones/bombushka-rm10.png", compra: "" },
    { nombre: "Western Cuban 800", foto: "img-coches/aviones/cuban-800.png", compra: "" },
    { nombre: "Dirigible de Atomic", foto: "img-coches/aviones/Dirigible-de-atomic.png", compra: "" },
    { nombre: "Dirigible de Xero", foto: "img-coches/aviones/dirigible-de-xero.png", compra: "" },
    { nombre: "Mammoth Dodo", foto: "img-coches/aviones/Mammoth-Dodo.png", compra: "" },
    { nombre: "Howard NX-25", foto: "img-coches/aviones/Howard-nx-25.png", compra: "" },
    { nombre: "Mammoth Hydra", foto: "img-coches/aviones/Mammoth-hydra.png", compra: "" },
    { nombre: "Jet", foto: "img-coches/aviones/Jet.png", compra: "" },
    { nombre: "Buckingham Luxor", foto: "img-coches/aviones/Buckingham-Luxor.png", compra: "" },
    { nombre: "Buckingham Luxor Deluxe", foto: "img-coches/aviones/Buckingham-Luxor-Deluxe.png", compra: "" },
    { nombre: "Western Mallard", foto: "img-coches/aviones/Western-Mallard.png", compra: "" },
    { nombre: "JoBuilt Mammatus", foto: "img-coches/aviones/JoBuilt-Mammatus.png", compra: "" },
    { nombre: "Buckingham Miljet", foto: "img-coches/aviones/Buckingham-Miljet.png", compra: "" },
    { nombre: "Mogul", foto: "img-coches/aviones/Mogul.png", compra: "" },
    { nombre: "Buckingham Nimbus", foto: "img-coches/aviones/Buckingham-Nimbus.png", compra: "" },
    { nombre: "P-45 Nokota", foto: "img-coches/aviones/P-45-Nokota.png", compra: "" },
    { nombre: "JoBuilt P-996 LAZER", foto: "img-coches/aviones/JoBuilt-P-996-LAZER.png", compra: "" },
    { nombre: "Pyro", foto: "img-coches/aviones/Pyro.png", compra: "" },
    { nombre: "Rogue", foto: "img-coches/aviones/Rogue.png", compra: "" },
    { nombre: "Western Seabreeze", foto: "img-coches/aviones/Western-Seabreeze.png", compra: "" },
    { nombre: "Buckingham Shamal", foto: "img-coches/aviones/Buckingham-shamal.png", compra: "" },
    { nombre: "Starling", foto: "img-coches/aviones/Starling.png", compra: "" },
    { nombre: "Titán", foto: "img-coches/aviones/Titán.png", compra: "" },
    { nombre: "Tula", foto: "img-coches/aviones/Tula.png", compra: "" },
    { nombre: "Pegassi Ultraligero", foto: "img-coches/aviones/Pegassi-Ultraligero.png", compra: "" },
    { nombre: "V-65 Molotok", foto: "img-coches/aviones/V-65-Molotok.png", compra: "" },
    { nombre: "JoBuilt Velum", foto: "img-coches/aviones/JoBuilt-Velum.png", compra: "" },
    { nombre: "JoBuilt Velum (5 asientos)", foto: "img-coches/aviones/JoBuilt-Velum-5-asientos.png", compra: "" },
    { nombre: "Buckingham Vestra", foto: "img-coches/aviones/Buckingham-Vestra.png", compra: "" },
    { nombre: "Volatol", foto: "img-coches/aviones/Volatol.png", compra: "" }
  ];
  