// Base de datos de aviones
const aviones = [
    { nombre: "Alpha-Z1", foto: "#", compra: "holaaa" },
    { nombre: "Mammoth Avenger", foto: "#", compra: "#" },
    { nombre: "Avión de carga", foto: "#", compra: "#" },
    { nombre: "Western Avioneta fumigadora", foto: "#", compra: "#" },
    { nombre: "Western Besra", foto: "#", compra: "#" },
    { nombre: "Bombushka", foto: "#", compra: "#" },
    { nombre: "Western Cuban 800", foto: "#", compra: "#" },
    { nombre: "Dirigible de Atomic", foto: "#", compra: "#" },
    { nombre: "Dirigible de Xero", foto: "#", compra: "#" },
    { nombre: "Mammoth Dodo", foto: "#", compra: "#" },
    { nombre: "Howard NX-25", foto: "#", compra: "#" },
    { nombre: "Mammoth Hydra", foto: "#", compra: "#" },
    { nombre: "Jet", foto: "#", compra: "#" },
    { nombre: "Buckingham Luxor", foto: "#", compra: "#" },
    { nombre: "Buckingham Luxor Deluxe", foto: "#", compra: "#" },
    { nombre: "Western Mallard", foto: "#", compra: "#" },
    { nombre: "JoBuilt Mammatus", foto: "#", compra: "#" },
    { nombre: "Buckingham Miljet", foto: "#", compra: "#" },
    { nombre: "Mogul", foto: "#", compra: "#" },
    { nombre: "Buckingham Nimbus", foto: "#", compra: "#" },
    { nombre: "P-45 Nokota", foto: "#", compra: "#" },
    { nombre: "JoBuilt P-996 LAZER", foto: "#", compra: "#" },
    { nombre: "Pyro", foto: "#", compra: "#" },
    { nombre: "Rogue", foto: "#", compra: "#" },
    { nombre: "Western Seabreeze", foto: "#", compra: "#" },
    { nombre: "Buckingham Shamal", foto: "#", compra: "#" },
    { nombre: "Starling", foto: "#", compra: "#" },
    { nombre: "Titán", foto: "#", compra: "#" },
    { nombre: "Tula", foto: "#", compra: "#" },
    { nombre: "Pegassi Ultraligero", foto: "#", compra: "#" },
    { nombre: "V-65 Molotok", foto: "#", compra: "#" },
    { nombre: "JoBuilt Velum", foto: "#", compra: "#" },
    { nombre: "JoBuilt Velum (5 asientos)", foto: "#", compra: "#" },
    { nombre: "Buckingham Vestra", foto: "#", compra: "#" },
    { nombre: "Volatol", foto: "#", compra: "#" }
  ];
  