const vehiculos = {
    
    deportivos: [
        {nombre: "Obey 9F", imagen: "#"},
        {nombre: "Obey 9F Cabrio", imagen: "#"},
        {nombre: "Albany Alpha 7", imagen: "#"},
        {nombre: "Bravado Banshee", imagen: "#"},
        {nombre: "Bravado Banshee sin toldo 8", imagen: "#"},
        {nombre: "Grotti Bestia GTS 25", imagen: "#"},
        {nombre: "Dinka Blista Compact 13", imagen: "#"},
        {nombre: "Bravado Buffalo", imagen: "#"},
        {nombre: "Bravado Buffalo S", imagen: "#"},
        {nombre: "Bravado Buffalo S (II)", imagen: "#"},
        {nombre: "Grotti Carbonizzare", imagen: "#"},
        {nombre: "Pfister Comet", imagen: "#"},
        {nombre: "Pfister Comet Retro personalizado 28", imagen: "#"},
        {nombre: "Pfister Comet Safari 32", imagen: "#"},
        {nombre: "Pfister Comet SR 32", imagen: "#"},
        {nombre: "Invetero Coquette", imagen: "#"},
        {nombre: "Invetero Coquette sin toldo", imagen: "#"},
        {nombre: "Declasse Drift Tampa 26", imagen: "#"},
        {nombre: "Annis Elegy Retro personalizado 28", imagen: "#"},
        {nombre: "Annis Elegy RH8 2", imagen: "#"},
        {nombre: "Benefactor Feltzer", imagen: "#"},
        {nombre: "Vapid Flash GT 33", imagen: "#"},
        {nombre: "Lampadati Furore GT 12", imagen: "#"},
        {nombre: "Schyster Fusilade", imagen: "#"},
        {nombre: "Karin Futo", imagen: "#"},
        {nombre: "Vapid GB200 33", imagen: "#"},
        {nombre: "Dinka Go Go Monkey Blista Compact 13", imagen: "#"},
        {nombre: "Declasse Hotring Sabre 33", imagen: "#"},
        {nombre: "Dinka Jester 7", imagen: "#"},
        {nombre: "Dinka Jester (de carreras) 14", imagen: "#"},
        {nombre: "Hijak Khamelion 1", imagen: "#"},
        {nombre: "Karin Kuruma 15", imagen: "#"},
        {nombre: "Karin Kuruma (armadura) 15", imagen: "#"},
        {nombre: "Ocelot Lynx 26", imagen: "#"},
        {nombre: "Dewbauchee Massacro 8", imagen: "#"},
        {nombre: "Dewbauchee Massacro (de carreras) 14", imagen: "#"},
        {nombre: "Pfister Neon 32", imagen: "#"},
        {nombre: "Obey Omnis 26", imagen: "#"},
        {nombre: "Ocelot Pariah 32", imagen: "#"},
        {nombre: "Maibatsu Penumbra", imagen: "#"},
        {nombre: "Coil Raiden 32", imagen: "#"},
        {nombre: "Dewbauchee Rapid GT", imagen: "#"},
        {nombre: "Dewbauchee Rapid GT convertible", imagen: "#"},
        {nombre: "BF Raptor 27", imagen: "#"},
        {nombre: "Ubermacht Revolter 32", imagen: "#"},
        {nombre: "Hijak Ruston 29", imagen: "#"},
        {nombre: "Benefactor Schafter LWB 20", imagen: "#"},
        {nombre: "Benefactor Schafter V12 20", imagen: "#"},
        {nombre: "Benefactor Schwartzer", imagen: "#"},
        {nombre: "Ubermacht Sentinel clásico 32", imagen: "#"},
        {nombre: "Dewbauchee Seven-70 25", imagen: "#"},
        {nombre: "Dewbauchee Specter 28", imagen: "#"},
        {nombre: "Dewbauchee Specter personalizado 28", imagen: "#"},
        {nombre: "Bravado Sprunk Buffalo 13", imagen: "#"},
        {nombre: "Benefactor Streiter 32", imagen: "#"},
        {nombre: "Karin Sultan", imagen: "#"},
        {nombre: "Benefactor Surano convertible", imagen: "#"},
        {nombre: "Lampadati Tropos Rallye 26", imagen: "#"},
        {nombre: "Bravado Verlierer 20", imagen: "#"}
    ],
    
    motos: [
        { nombre: "Dinka Akuma", imagen: "#"},
        { nombre: "LCC Avarus", imagen: "#"},
        { nombre: "Western Bagger", imagen: "#"},
        { nombre: "Pegassi Bati 801", imagen: "#"},
        { nombre: "Pegassi Bati 801RR", imagen: "#"},
        { nombre: "Nagasaki BF400", imagen: "#"},
        { nombre: "Nagasaki Carbon RS", imagen: "#"},
        { nombre: "Nagasaki Chimera", imagen: "#"},
        { nombre: "Western Cliffhanger", imagen: "#"},
        { nombre: "Western Daemon", imagen: "#"},
        { nombre: "Western Daemon personalizada", imagen: "#"},
        { nombre: "Shitzu Defiler", imagen: "#"},
        { nombre: "Principe Diabolus", imagen: "#"},
        { nombre: "Principe Diabolus personalizada", imagen: "#"},
        { nombre: "Dinka Double-T", imagen: "#"},
        { nombre: "Dinka Enduro", imagen: "#"},
        { nombre: "Pegassi Esskey", imagen: "#"},
        { nombre: "Pegassi Faggio", imagen: "#"},
        { nombre: "Pegassi Faggio Mod", imagen: "#"},
        { nombre: "Pegassi Faggio Sport", imagen: "#"},
        { nombre: "Pegassi FCR 1000", imagen: "#"},
        { nombre: "Pegassi FCR 1000 personalizada", imagen: "#"},
        { nombre: "Western Gargoyle", imagen: "#"},
        { nombre: "Shitzu Hakuchou", imagen: "#"},
        { nombre: "Shitzu Hakuchou Drag", imagen: "#"},
        { nombre: "LCC Hexer", imagen: "#"},
        { nombre: "LCC Innovation", imagen: "#"},
        { nombre: "Principe Lectro", imagen: "#"},
        { nombre: "Maibatsu Manchez", imagen: "#"},
        { nombre: "Western Moto desgastada", imagen: "#"},
        { nombre: "Principe Nemesis", imagen: "#"},
        { nombre: "Western Nightblade", imagen: "#"},
        { nombre: "Pegassi Oppressor", imagen: "#"},
        { nombre: "Shitzu PCJ 600", imagen: "#"},
        { nombre: "Pegassi Ruffian", imagen: "#"},
        { nombre: "Maibatsu Sánchez", imagen: "#"},
        { nombre: "Maibatsu Sánchez (tapicería)", imagen: "#"},
        { nombre: "LCC Sanctus", imagen: "#"},
        { nombre: "Nagasaki Shotaro", imagen: "#"},
        { nombre: "Western Sovereign", imagen: "#"},
        { nombre: "Dinka Thrust", imagen: "#"},
        { nombre: "Shitzu Vader", imagen: "#"},
        { nombre: "Dinka Vindicator", imagen: "#"},
        { nombre: "Pegassi Vortex", imagen: "#"},
        { nombre: "Western Wolfsbane", imagen: "#"},
        { nombre: "Western Zombie Bobber", imagen: "#"},
        { nombre: "Western Zombie Chopper", imagen: "#"}
    ],
}