// Base de datos de motos
const motos = [
    { nombre: "Dinka Akuma", foto: "#", compra: "#" },
    { nombre: "LCC Avarus", foto: "#", compra: "#" },
    { nombre: "Western Bagger", foto: "#", compra: "#" },
    { nombre: "Pegassi Bati 801", foto: "#", compra: "#" },
    { nombre: "Pegassi Bati 801RR", foto: "#", compra: "#" },
    { nombre: "Nagasaki BF400", foto: "#", compra: "#" },
    { nombre: "Nagasaki Carbon RS", foto: "#", compra: "#" },
    { nombre: "Nagasaki Chimera", foto: "#", compra: "#" },
    { nombre: "Western Cliffhanger", foto: "#", compra: "#" },
    { nombre: "Western Daemon", foto: "#", compra: "#" },
    { nombre: "Western Daemon personalizada", foto: "#", compra: "#" },
    { nombre: "Shitzu Defiler", foto: "#", compra: "#" },
    { nombre: "Principe Diabolus", foto: "#", compra: "#" },
    { nombre: "Principe Diabolus personalizada", foto: "#", compra: "#" },
    { nombre: "Dinka Double-T", foto: "#", compra: "#" },
    { nombre: "Dinka Enduro", foto: "#", compra: "#" },
    { nombre: "Pegassi Esskey", foto: "#", compra: "#" },
    { nombre: "Pegassi Faggio", foto: "#", compra: "#" },
    { nombre: "Pegassi Faggio Mod", foto: "#", compra: "#" },
    { nombre: "Pegassi Faggio Sport", foto: "#", compra: "#" },
    { nombre: "Pegassi FCR 1000", foto: "#", compra: "#" },
    { nombre: "Pegassi FCR 1000 personalizada", foto: "#", compra: "#" },
    { nombre: "Western Gargoyle", foto: "#", compra: "#" },
    { nombre: "Shitzu Hakuchou", foto: "#", compra: "#" },
    { nombre: "Shitzu Hakuchou Drag", foto: "#", compra: "#" },
    { nombre: "LCC Hexer", foto: "#", compra: "#" },
    { nombre: "LCC Innovation", foto: "#", compra: "#" },
    { nombre: "Principe Lectro", foto: "#", compra: "#" },
    { nombre: "Maibatsu Manchez", foto: "#", compra: "#" },
    { nombre: "Western Moto desgastada", foto: "#", compra: "#" },
    { nombre: "Principe Nemesis", foto: "#", compra: "#" },
    { nombre: "Western Nightblade", foto: "#", compra: "#" },
    { nombre: "Pegassi Oppressor", foto: "#", compra: "#" },
    { nombre: "Shitzu PCJ 600", foto: "#", compra: "#" },
    { nombre: "Pegassi Ruffian", foto: "#", compra: "#" },
    { nombre: "Maibatsu Sánchez", foto: "#", compra: "#" },
    { nombre: "Maibatsu Sánchez (tapicería)", foto: "#", compra: "#" },
    { nombre: "LCC Sanctus", foto: "#", compra: "#" },
    { nombre: "Nagasaki Shotaro", foto: "#", compra: "#" },
    { nombre: "Western Sovereign", foto: "#", compra: "#" },
    { nombre: "Dinka Thrust", foto: "#", compra: "#" },
    { nombre: "Shitzu Vader", foto: "#", compra: "#" },
    { nombre: "Dinka Vindicator", foto: "#", compra: "#" },
    { nombre: "Pegassi Vortex", foto: "#", compra: "#" },
    { nombre: "Western Wolfsbane", foto: "#", compra: "#" },
    { nombre: "Western Zombie Bobber", foto: "#", compra: "#" },
    { nombre: "Western Zombie Chopper", foto: "#", compra: "#" }
  ];
  