// Base de datos de vehículos Todoterrenos
const todoterrenos = [
    { nombre: "BF Bifta", foto: "#", compra: "#" },
    { nombre: "Nagasaki Blazer", foto: "#", compra: "#" },
    { nombre: "Nagasaki Blazer Aqua", foto: "#", compra: "#" },
    { nombre: "Nagasaki Blazer Lifeguard", foto: "#", compra: "#" },
    { nombre: "Canis Bodhi", foto: "#", compra: "#" },
    { nombre: "Coil Brawler", foto: "#", compra: "#" },
    { nombre: "HVY Camioneta Insurgent", foto: "#", compra: "#" },
    { nombre: "Vapid Caracara", foto: "#", compra: "#" },
    { nombre: "Vapid Desert Raid", foto: "#", compra: "#" },
    { nombre: "Dubsta 6x6 Dubsta 6x6", foto: "#", compra: "#" },
    { nombre: "BF Dune Buggy", foto: "#", compra: "#" },
    { nombre: "BF Dune FAV", foto: "#", compra: "#" },
    { nombre: "Bravado Duneloader", foto: "#", compra: "#" },
    { nombre: "Nagasaki Hot Rod Blazer", foto: "#", compra: "#" },
    { nombre: "BF Injection", foto: "#", compra: "#" },
    { nombre: "HVY Insurgent (cubierto)", foto: "#", compra: "#" },
    { nombre: "HVY Insurgent personalizada", foto: "#", compra: "#" },
    { nombre: "Canis Kalahari", foto: "#", compra: "#" },
    { nombre: "Canis Kalahari sin toldo", foto: "#", compra: "#" },
    { nombre: "Canis Kamacho", foto: "#", compra: "#" },
    { nombre: "Cheval Marshall", foto: "#", compra: "#" },
    { nombre: "Canis Mesa (II)", foto: "#", compra: "#" },
    { nombre: "Canis Mesa (III)", foto: "#", compra: "#" },
    { nombre: "HVY Nightshark", foto: "#", compra: "#" },
    { nombre: "BF Ramp Buggy", foto: "#", compra: "#" },
    { nombre: "Declasse Rancher XL", foto: "#", compra: "#" },
    { nombre: "Declasse Rancher XL (II)", foto: "#", compra: "#" },
    { nombre: "Karin Rebel", foto: "#", compra: "#" },
    { nombre: "Karin Rebel (limpio)", foto: "#", compra: "#" },
    { nombre: "Vapid Riata", foto: "#", compra: "#" },
    { nombre: "Vapid Sandking SWB", foto: "#", compra: "#" },
    { nombre: "Vapid Sandking XL", foto: "#", compra: "#" },
    { nombre: "Space Docker", foto: "#", compra: "#" },
    { nombre: "Nagasaki Street Blazer", foto: "#", compra: "#" },
    { nombre: "Karin Technical", foto: "#", compra: "#" },
    { nombre: "Karin Technical Aqua", foto: "#", compra: "#" },
    { nombre: "Karin Technical personalizada", foto: "#", compra: "#" },
    { nombre: "The Liberator", foto: "#", compra: "#" },
    { nombre: "Vapid Trophy Truck", foto: "#", compra: "#" }
  ];
  