// Base de datos de vehículos Todoterrenos
const todoterrenos = [
    { nombre: "BF Bifta 3", foto: "#", compra: "#" },
    { nombre: "Nagasaki Blazer", foto: "#", compra: "#" },
    { nombre: "Nagasaki Blazer Aqua 28", foto: "#", compra: "#" },
    { nombre: "Nagasaki Blazer Lifeguard", foto: "#", compra: "#" },
    { nombre: "Canis Bodhi", foto: "#", compra: "#" },
    { nombre: "Coil Brawler 17", foto: "#", compra: "#" },
    { nombre: "HVY Camioneta Insurgent 15", foto: "#", compra: "#" },
    { nombre: "Vapid Caracara 33", foto: "#", compra: "#" },
    { nombre: "Vapid Desert Raid 26", foto: "#", compra: "#" },
    { nombre: "Dubsta 6x6 Dubsta 6x6 9", foto: "#", compra: "#" },
    { nombre: "BF Dune Buggy", foto: "#", compra: "#" },
    { nombre: "BF Dune FAV 30", foto: "#", compra: "#" },
    { nombre: "Bravado Duneloader", foto: "#", compra: "#" },
    { nombre: "Nagasaki Hot Rod Blazer", foto: "#", compra: "#" },
    { nombre: "BF Injection", foto: "#", compra: "#" },
    { nombre: "HVY Insurgent (cubierto) 15", foto: "#", compra: "#" },
    { nombre: "HVY Insurgent personalizada 30", foto: "#", compra: "#" },
    { nombre: "Canis Kalahari 3", foto: "#", compra: "#" },
    { nombre: "Canis Kalahari sin toldo 12", foto: "#", compra: "#" },
    { nombre: "Canis Kamacho 32", foto: "#", compra: "#" },
    { nombre: "Cheval Marshall 13", foto: "#", compra: "#" },
    { nombre: "Canis Mesa (II) 5", foto: "#", compra: "#" },
    { nombre: "Canis Mesa (III)", foto: "#", compra: "#" },
    { nombre: "HVY Nightshark 30", foto: "#", compra: "#" },
    { nombre: "BF Ramp Buggy 28", foto: "#", compra: "#" },
    { nombre: "Declasse Rancher XL", foto: "#", compra: "#" },
    { nombre: "Declasse Rancher XL (II)", foto: "#", compra: "#" },
    { nombre: "Karin Rebel 5", foto: "#", compra: "#" },
    { nombre: "Karin Rebel (limpio)", foto: "#", compra: "#" },
    { nombre: "Vapid Riata 32", foto: "#", compra: "#" },
    { nombre: "Vapid Sandking SWB", foto: "#", compra: "#" },
    { nombre: "Vapid Sandking XL", foto: "#", compra: "#" },
    { nombre: "Space Docker", foto: "#", compra: "#" },
    { nombre: "Nagasaki Street Blazer 27", foto: "#", compra: "#" },
    { nombre: "Karin Technical 15", foto: "#", compra: "#" },
    { nombre: "Karin Technical Aqua 28", foto: "#", compra: "#" },
    { nombre: "Karin Technical personalizada 30", foto: "#", compra: "#" },
    { nombre: "The Liberator 10", foto: "#", compra: "#" },
    { nombre: "Vapid Trophy Truck 26", foto: "#", compra: "#" }
  ];
  